package com.jessebrault.gst.tokenizer;

public enum TokenType {
    TEXT,
    DOLLAR_REFERENCE_DOLLAR,
    DOLLAR_REFERENCE_BODY,

    BLOCK_SCRIPTLET_OPEN,
    EXPRESSION_SCRIPTLET_OPEN,
    SCRIPTLET_BODY,
    SCRIPTLET_CLOSE,

    IMPORT_BLOCK_OPEN,
    IMPORT_BLOCK_BODY,
    IMPORT_BLOCK_CLOSE,

    DOLLAR_SCRIPTLET_OPEN,
    DOLLAR_SCRIPTLET_BODY,
    DOLLAR_SCRIPTLET_CLOSE
}
